### ISSUE TITLE
Improve linting performance and coverage

### ISSUE THREAD

**Issue by thomasnordquist** [VIISON/style-guide#4]
Currently eslint checks all `*.js` files of the current project upon commit.
This makes committing rather slow and painful.

Currently the pre-commit hook checks every `*.php` file that has changed and every `*.js` file in the project.

I'd propose that we only change `*.php` & `*.js` files that have changes in the pre-commit hook.
In addition a complete check of the project with phpcs and eslint in the pre-push hook should be implemented.

This way `commits` can be done a lot faster and code style can be guaranteed with the not-as-frequently-executed `push`.

Any thoughts ?
@fixpunkt, @svenmuennich

**Comment by svenmuennich** [comment]
All plugins that should be linted contain `phpcs.xml`.
